kings = {
     'Alarico I',
     'Ataúlfo',
     'Sigerico',
     'Walia',
     'Teodorico I',
     'Turismundo',
     'Teodorico II',
     'Eurico',
     'Alarico II',
     'Gesaleico',
     'Amalarico',
     'Teudis',
     'Teudiselo',
     'Agila I',
     'Atanagildo',
     'Liuva I',
     'Leovigildo',
     'Recaredo I',
     'Liuva II',
     'Witerico',
     'Gundemaro',
     'Sisebuto',
     'Recaredo II',
     'Suintila',
     'Sisenando',
     'Chintila',
     'Tulga',
     'Chindasvinto',
     'Recesvinto',
     'Wamba',
     'Ervigio',
     'Égica',
     'Witiza',
     'Agila II',
     'Ardón'
}
