#!/bin/sh

### BEGIN INIT INFO
# Provides:          marcod
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: The marcopolo discoverer
# Description:       Marcopolo is a service discovering protocol
#                    based on multicast messaging.
### END INIT INFO

# Author: Diego Martin <martinarroyo@usal.es>
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
TWISTED_NAME="marcod"
DAEMON=/usr/bin/twistd
SERVICE_NAME="/etc/marcopolo/daemon/marco_twistd.tac"
#SERVICE_DIR=/home/user/twistedplugin

PIDFILE=/var/run/marcopolo/${TWISTED_NAME}.pid
LOGFILE=/var/log/marcopolo/${TWISTED_NAME}-twistd.log

DAEMON_OPTS="--pidfile=$PIDFILE --logfile=$LOGFILE -y $SERVICE_NAME"

# Set python path so twistd can find the plugin
# See: http://twistedmatrix.com/projects/core/documentation/howto/plugin.html
#export PYTHONPATH=$SERVICE_DIR

if [ ! -x $DAEMON ]; then
  echo "ERROR: Can't execute $DAEMON."
  exit 1
fi

# if [ ! -d $SERVICE_DIR ]; then
#   echo "ERROR: Directory doesn't exist: $SERVICE_DIR"
#   exit 1
# fi

start_service() {
  echo -n " * Starting $SERVICE_NAME... "
  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
  e=$?
  if [ $e -eq 1 ]; then
    echo "already running"
    return
  fi

  if [ $e -eq 255 ]; then
    echo "couldn't start :("
    return
  fi

  echo "done"
}

stop_service() {
  echo -n " * Stopping $SERVICE_NAME... "
  start-stop-daemon -Kq -R 10 -p $PIDFILE
  e=$?
  if [ $e -eq 1 ]; then
    echo "not running"
    return
  fi

  echo "done"
}

case "$1" in
  start)
    start_service
    ;;
  stop)
    stop_service
    ;;
  restart)
    stop_service
    start_service
    ;;
  *)
    echo "Usage: /etc/init.d/$SERVICE_NAME {start|stop|restart}" >&2
    exit 1   
    ;;
esac

exit 0